### PR TITLE
chore(deps): try supporting GraphQL v16

### LINKED ISSUE #773: GraphQL v16
### Feature description

Support for GraphQL v16. I'm aware of the exploration in https://github.com/graphile/graphile-engine/pull/764, but I wanted to open this for tracking purposes.

I'm currently only using `graphql-parse-resolve-info`.

### Motivating example

Latest features, etc.

### Breaking changes

Dropping support for Node 8 and Node 10, but these are EOL anyway.

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [ ] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

### PR DESCRIPTION
**Pull request by benjie**
GraphQL v16 doesn't support Node 8 or Node 10 or older versions of Node 12, so we cannot merge all of this, I'm opening it primarily to see if CI will pass on Node 12+.

Fixes #773

### CODE REVIEW

**Comment by glen-84** [comment]
Why do you need to support EOL versions of Node.js?

**Comment by benjie** [comment]
I agree; and will be officially and explicitly not supporting EOL versions of Node, Postgres, GraphQL, etc from V5 onwards. However this was not stated in the V4.0.0 release and I want to stay within semver which is somewhat fuzzy on the topic but there has definitely been pushback on removing support.

**Comment by glen-84** [comment]
It looks like `getArgumentValues` is no longer available. There's a related issue @ https://github.com/graphql/graphql-js/issues/2719.

**Comment by boredland** [comment]
Is there anything I can do to help with this migration / what is the state of it right now?

**Comment by benjie** [comment]
According to the GraphQL.js WG yesterday a fix to the above issue is being worked on. Please follow that thread linked above.

**Comment by hiepxanh** [comment]
`getArgumentValues` is available for now since it merged https://github.com/graphql/graphql-js/pull/3487

**Comment by sachaw** [comment]
Any chance we can get an update on this? It's a major blocker for several down stream packages. Thanks.

**Comment by benjie** [comment]
Rebased, GraphQL version bumped in the lockfile, added a few type workarounds. Fingers crossed :crossed_fingers:

**Comment by benjie** [comment]
Alas, more work is required to support V16 without breaking backwards compatibility with previously supported versions of GraphQL. My time is currently focussed on developing PostGraphile V5, but if you wanted to raise a PR against this PR to make the necessary changes you're welcome to - I suspect it's mostly signature changes on the various methods where object parameters are now required instead of positional arguments.

I don't personally see this as much of a priority because it's still perfectly reasonable to use GraphQL v15 and there's no features in v16 that PostGraphile v4 needs. If I'm missing something, please feel free to let me know what critical reasons there are for using GraphQL v16 rather than v15 :+1:

**Comment by hiepxanh** [comment]
I agree with you, let's focus on PostGraphile V5. We just fine, sometime the npm install auto upgrade cause we frustrated and then the feeling of everything perfect make us need the new version must be up to date, but after all it just fine. haha

**Review by jmarsal — APPROVED** [review]
OK

**Comment by benjie** [comment]
If you need GraphQL v16 support, use PostGraphile V5 :+1:

**Pull request closed without merging**
