### PR TITLE
chore(flow): upgrade flow to the latest version, fix/mute all flow er…

### PR DESCRIPTION
**Pull request by none23**
I realize that flow is being removed, but an up-to-date version probably won't hurt, as it works better with graphql-js types

### CODE REVIEW

**Comment by benjie** [comment]
Ugh. Flow.

**Comment by benjie** [comment]
@none23 Please give this the once-over and let me know you're happy with my changes :+1: 

(Please do not force-push.)

**Comment by none23** [comment]
Yeah, looks great!

**Comment by benjie** [comment]
Thanks; this has given me more impetus to work on the TypeScript conversion :)

**Pull request merged**
