### PR TITLE
feat: allow granular list nulls in nullability

### PR DESCRIPTION
**Pull request by kevboh**
In the makeChangeNullability plugin, for list types, adds the ability to specify if both the list type itself should be nullable _and_ if its member type should be nullable, allowing you to get the following GraphQL type signature:

```
someList: [MyType!]!
```

### CODE REVIEW

**Comment by kevboh** [comment]
I would like to also update the corresponding docs, but I'm not sure where they're stored.

**Comment by benjie** [comment]
I've thought about this a bit more and it's possible to have things like:

```graphql
type Bar {
  foo: [[[Int!]]!]
}
```

So `listType` and `namedType` aren't quite enough.

Maybe we could do `listType: [boolean]`

Then we could have:

```js
{ Bar: { foo: {
  listType: [false, true, false],
  namedType: true
}}}
```

That'd change it to:

```graphql
type Bar {
  foo: [[[Int]!]]!
}
```

I think this is going to have to walk the types manually using the `.kind` (or `.kindOf`? I forget) property on the types, calling `getNullableType` at each point. We should also allow `null`/`undefined` to just keep the previous nullability.

I totally understand if you'd rather I wrote this :grin:

**Comment by benjie** [comment]
Regarding the docs, at the top of every page is a "Suggest improvements to this page" link that takes you to the edit flow on GitHub. https://www.graphile.org/postgraphile/make-change-nullability-plugin/

**Comment by kevboh** [comment]
@benjie oh, interesting. That change would definitely require more learning around the GraphQL APIs on my part, but I could do it if you're okay with this stretching out a few weeks—I'm pretty slammed at the moment.

**Comment by benjie** [comment]
Me too; stretch it out :+1:

**Comment by benjie** [comment]
@kevboh I'm going to close this for now as no-one else has requested this feature; feel free to reopen it when you get a chance to address the feedback :+1:

**Comment by kevboh** [comment]
@benjie yep, no worries. The hacky plugin we've been using for this continues to work well, but isn't really portable. Happy to put in the work to make it so if others need it.

**Pull request closed without merging**
