### PR TITLE
feat(graphile-utils): Type update on addPgTableOrderByPlugin

### PR DESCRIPTION
**Pull request by hansololai**
The current `makeAddPgTableOrderByPlugin` provie a utilility function `orderByAscDesc`. The current typescript only allows either a `string` or a `SQL` element to be passed in, but the code actually handles the case (and it is also in the doc) to pass in a function `{queryBuilder} => SQL`. This PR updates that typescript definition of the function and also the orderbySpec.

### CODE REVIEW

**Comment by hansololai** [comment]
Interestingly when I run yarn lint:fix, it also fixed a bunch of README.md file's js syntax.  for the purpose of this PR, I did not commit those.

**Comment by benjie** [comment]
Maybe you have prettier installed globally and it's using that rather than ours? :shrug:

**Comment by benjie** [comment]
Please could you rebase this on the `v4` (default) branch? `master` is not used any more. That might explain your formatting woes too.

**Comment by hansololai** [comment]
The rebasing got a lot of conflicts, I didn't want to mess up other stuff so I made another PR from v4 to v4. https://github.com/graphile/graphile-engine/pull/629

**Pull request closed without merging**
