### PR TITLE
docs: fixed indentation in README code blocks

### PR DESCRIPTION
**Pull request by jguddas**
## Description

Just fixing some indentation issues.

## Performance impact

None.

## Security impact

None.

## Checklist

- [x] My code matches the project's code style and `yarn lint:fix` passes.
- [ ] I've added tests for the new feature, and `yarn test` passes.
- [ ] I have detailed the new feature in the relevant documentation.
- [ ] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [ ] If this is a breaking change I've explained why.

### CODE REVIEW

**Review by benjie — APPROVED** [review]
Weird that this isn't formatted by `prettier` :man_shrugging:

**Comment by benjie** [comment]
Oh; you've raised this PR against `master` which is _ancient_. Please see the `v4` branch for latest.

**Comment by jguddas** [comment]
You could consider changing the default branch.

**Comment by benjie** [comment]
The default branch _is_ `v4`.

**Pull request closed without merging**
