### PR TITLE
wal2json is now available on Homebrew

### PR DESCRIPTION
**Pull request by singingwolfboy**
https://github.com/Homebrew/homebrew-core/pull/45010

### CODE REVIEW

**Comment by benjie** [comment]
(The latter is particularly problematic if you have postgis installed as it doesn’t allow the data migration to take place under certain circumstances, e.g. if homebrew deletes the old postgres binaries before you’ve had a chance to migrate the data.)

**Comment by singingwolfboy** [comment]
> Also can you confirm that doing the homebrew install won’t force you to upgrade postgres to the latest (e.g. 12)

I'm pretty sure that Homebrew _does_ automatically upgrade dependencies when installing a new package, and postgres is a dependency of wal2json. Maybe it's simpler to just not mention the Homebrew option, given all of these caveats...

**Comment by benjie** [comment]
I think that might be wise; alternatively we can just suggest afterwards "wal2json is also available via Homebrew on Mac". I think the current install instructions are probably least likely to cause the user issues 👍

**Comment by benjie** [comment]
I'm going to close this for now :+1:

**Pull request closed without merging**
