### PR TITLE
feat(pg): support domain constrained composite types

### PR DESCRIPTION
**Pull request by jcgsville**
Addresses https://github.com/graphile/graphile-engine/issues/600

Input types now support domains that constrain composite types instead of failing to generate the schema on startup.

I didn't add any testing as I was a bit unclear what the testing story is for a change like this. Happy to make any additions in this area with a quick point in the right direction.

### CODE REVIEW

**Comment by benjie** [comment]
Thanks @jcgsville; this is effectively a new type so we should add it to `b.types`:

https://github.com/graphile/graphile-engine/blob/e863fd37bddd1a7d40bd6e5e90f5065d1e64949b/packages/postgraphile-core/__tests__/kitchen-sink-schema.sql#L237

Also add a mutation test for it in here:

https://github.com/graphile/graphile-engine/blob/v4/packages/postgraphile-core/__tests__/fixtures/mutations/types.graphql

And a query test here:

https://github.com/graphile/graphile-engine/blob/v4/packages/postgraphile-core/__tests__/fixtures/queries/types.graphql

These are all integration tests, effectively.

Changes to the above will require a lot of snapshot updates, you can run `yarn --cwd packages/postgraphile-core jest -u` to update them. You may need to fix a few other tests too - let the test results guide you.

Thanks!

**Comment by jcgsville** [comment]
Thanks for the guidance @benjie! I added some tests, which pass with Postgres 11, but it looks like Postgres 10 and earlier did not let you create a domain over a composite type, so the tests fail there. Is there a mechanism testing things only in certain versions?

**Comment by benjie** [comment]
@jcgsville Not a good one, but we did have to avoid PG10 tests running in PG9.6: https://github.com/graphile/graphile-engine/blob/9dca5c8631e6c336b59c499d901c774d41825c60/packages/postgraphile-core/scripts/test#L47-L54

I'm not happy with our testing system in general (it's very legacy, clunky and slow), and am planning to overhaul it as part of the work I'm doing on V5.

**Comment by benjie** [comment]
@jcgsville Are you able to add a relevant workaround for PG11 as indicated above?

**Comment by benjie** [comment]
Merged `v4` branch and then moved the test of this feature to the PG11 test suite.

**Review by benjie — APPROVED** [review]
Thanks for the fix :raised_hands:

**Comment by jcgsville** [comment]
Sorry to have not gotten to the testing tweaks sooner. Thanks for ferrying it the rest of the way through 🙂

**Comment by benjie** [comment]
No worries 🙌

**Pull request merged**
